<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LumioProduction>false</LumioProduction>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Lumio.Client.Input.Tests</RootNamespace>
    <AssemblyName>Lumio.Client.Input.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\src\Lumio.Client.Input.csproj" />
  </ItemGroup>
</Project>
