<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lumio.Client.Bot</RootNamespace>
    <AssemblyName>Lumio.Client.Bot</AssemblyName>
    <Description>LumioClient bot module</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Lumio.Client.Bot.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\session\src\Lumio.Client.Session.csproj" />
    <ProjectReference Include="..\..\input\src\Lumio.Client.Input.csproj" />
    <ProjectReference Include="..\..\observability\src\Lumio.Client.Observability.csproj" />
  </ItemGroup>
</Project>
