<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Lumio.Client.Handshake</RootNamespace>
    <AssemblyName>Lumio.Client.Handshake</AssemblyName>
    <Description>LumioClient handshake module</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Lumio.Client.Handshake.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\connection\src\Lumio.Client.Connection.csproj" />
    <ProjectReference Include="..\..\observability\src\Lumio.Client.Observability.csproj" />
  </ItemGroup>
</Project>
